[package]
name = "ox-server"
version.workspace = true
edition.workspace = true

[dependencies]
ox-core = { path = "../core" }
ox-dataflow = { path = "../dataflow" }
ox-langs = { path = "../langs" }
axum = "0.8"
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
anyhow.workspace = true
ignore = "0.4"
globset = "0.4"
